import React from 'react';
import type { Recipe, Difficulty } from '../types';
import jsPDF from 'jspdf';
import DifficultyMeter from './DifficultyMeter';

const ImagePlaceholder = () => (
    <div className="w-full h-64 bg-slate-200 flex items-center justify-center animate-pulse">
        <svg className="w-12 h-12 text-slate-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
    </div>
);

interface RecipeCardProps {
    recipe: Recipe;
    language: 'en' | 'es';
    onToggleFavorite: (recipe: Recipe) => void;
    isFavorite: boolean;
    onShare: (recipe: Recipe) => void;
}

const RecipeCard: React.FC<RecipeCardProps> = ({ recipe, language, onToggleFavorite, isFavorite, onShare }) => {
    
    const handleDownloadPdf = () => {
        const doc = new jsPDF({
            orientation: 'p',
            unit: 'mm',
            format: 'a4'
        });

        // --- Document Setup ---
        const pageW = doc.internal.pageSize.getWidth();
        const pageH = doc.internal.pageSize.getHeight();
        const margin = 15;
        const contentW = pageW - margin * 2;
        const pageBottom = pageH - 15;
        let yPos = 0;

        // --- Colors ---
        const primaryColor = '#22c55e'; // green-500
        const textColorDark = '#1e293b'; // slate-800
        const textColorMedium = '#475569'; // slate-600
        const textColorLight = '#64748b'; // slate-500
        const bgSlate = '#f1f5f9'; // slate-100 for contrast
        const borderSlate = '#e2e8f0'; // slate-200

        // --- Helper Functions ---
        const addFooter = () => {
            doc.setFontSize(8);
            doc.setFont('helvetica', 'italic');
            doc.setTextColor(textColorLight);
            doc.text('Generated by NutriChef', pageW / 2, pageH - 7, { align: 'center' });
        };

        const addHeader = () => {
            doc.setFillColor(primaryColor);
            doc.rect(0, 0, pageW, 18, 'F');
            doc.setFontSize(18);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor('#FFFFFF');
            doc.text('NutriChef', margin, 12);
            yPos = 18 + margin;
        };

        // --- 1. Header ---
        addHeader();

        // --- 2. Recipe Title & Description ---
        doc.setFontSize(24);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(textColorDark);
        const titleLines = doc.splitTextToSize(recipe.recipeName, contentW);
        doc.text(titleLines, pageW / 2, yPos, { align: 'center' });
        yPos += titleLines.length * 9 + 6;

        doc.setFontSize(11);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(textColorMedium);
        const descriptionLines = doc.splitTextToSize(recipe.description, contentW - 10);
        doc.text(descriptionLines, pageW / 2, yPos, { align: 'center' });
        yPos += descriptionLines.length * 4.5 + 10;

        // --- 3. Image ---
        if (recipe.imageUrl) {
            try {
                const imgData = recipe.imageUrl;
                const ratio = 16 / 9;
                const finalW = contentW;
                const finalH = finalW / ratio;
                if (yPos + finalH < pageBottom) {
                    doc.addImage(imgData, 'JPEG', margin, yPos, finalW, finalH, undefined, 'FAST');
                    yPos += finalH + 10;
                }
            } catch (e) { console.error("Could not add image to PDF", e); }
        }

        // --- 4. Meta Info Panel ---
        const infoBoxY = yPos;
        const infoBoxHeight = 18;
        if (infoBoxY + infoBoxHeight < pageBottom) {
            doc.setFillColor(bgSlate);
            doc.setDrawColor(borderSlate);
            doc.roundedRect(margin, infoBoxY, contentW, infoBoxHeight, 3, 3, 'FD');

            const items = [
                { label: language === 'es' ? 'Raciones' : 'Servings', value: String(recipe.servings) },
                { label: 'Prep', value: recipe.prepTime },
                { label: 'Cook', value: recipe.cookTime },
                { label: language === 'es' ? 'Calorías' : 'Calories', value: `~${recipe.calories} kcal` }
            ];

            const colWidth = contentW / 4;
            const labelY = infoBoxY + 7;
            const valueY = infoBoxY + 13;

            items.forEach((item, index) => {
                const x = margin + (colWidth * index) + (colWidth / 2);
                
                doc.setFontSize(8);
                doc.setFont('helvetica', 'bold');
                doc.setTextColor(textColorLight);
                doc.text(item.label.toUpperCase(), x, labelY, { align: 'center' });

                doc.setFontSize(10);
                doc.setFont('helvetica', 'bold');
                doc.setTextColor(textColorDark);
                doc.text(item.value, x, valueY, { align: 'center' });
            });

            yPos += infoBoxHeight + 10;
        }
        
        // --- 5. Nutrition & Difficulty Panel ---
        if (yPos + 25 < pageBottom) {
            doc.setFillColor(bgSlate);
            doc.setDrawColor(borderSlate);
            doc.roundedRect(margin, yPos, contentW, 25, 3, 3, 'FD');
            
            // Nutrition Section
            if (recipe.nutrition) {
                const nutritionY = yPos + 7;
                const colWidth = contentW / 3;
                const nutritionItems = [
                    { label: language === 'es' ? 'Proteína' : 'Protein', value: recipe.nutrition.protein },
                    { label: language === 'es' ? 'Carbs' : 'Carbs', value: recipe.nutrition.carbs },
                    { label: language === 'es' ? 'Grasas' : 'Fats', value: recipe.nutrition.fats },
                ];
                nutritionItems.forEach((item, index) => {
                    const x = margin + (colWidth * index) + (colWidth / 2);
                    doc.setFontSize(8);
                    doc.setFont('helvetica', 'bold');
                    doc.setTextColor(textColorLight);
                    doc.text(item.label.toUpperCase(), x, nutritionY, { align: 'center' });

                    doc.setFontSize(12);
                    doc.setFont('helvetica', 'bold');
                    doc.setTextColor(primaryColor);
                    doc.text(item.value, x, nutritionY + 6, { align: 'center' });
                });
            }
            
            // Difficulty Meter
            const difficultyMap: Record<Difficulty, { level: number; label: { en: string; es: string; } }> = {
                'Very Easy': { level: 1, label: { en: 'Very Easy', es: 'Muy Fácil' } },
                'Easy': { level: 2, label: { en: 'Easy', es: 'Fácil' } },
                'Medium': { level: 3, label: { en: 'Medium', es: 'Media' } },
                'Hard': { level: 4, label: { en: 'Hard', es: 'Difícil' } },
                'Expert': { level: 5, label: { en: 'Expert', es: 'Experta' } }
            };
            const { level, label } = difficultyMap[recipe.difficulty] || difficultyMap['Medium'];
            const meterY = yPos + 18;
            const barTotalWidth = contentW * 0.4;
            const barStartX = margin + contentW - barTotalWidth - 4;

            doc.setFontSize(9);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(textColorDark);
            doc.text(`${language === 'es' ? 'Dificultad' : 'Difficulty'}:`, margin + 4, meterY + 2.5);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(textColorMedium);
            doc.text(label[language], margin + 28, meterY + 2.5);
            
            doc.setDrawColor(borderSlate);
            const barWidth = barTotalWidth / 5;
            for (let i = 0; i < 5; i++) {
                const barX = barStartX + (i * barWidth);
                doc.setFillColor(i < level ? primaryColor : '#FFFFFF');
                doc.rect(barX, meterY, barWidth - 1, 3, 'FD');
            }
            yPos += 25 + 10;
        }

        // --- 6. Ingredients & Instructions (Two Columns) ---
        const columnsStartY = yPos;
        let yPosLeft = columnsStartY;
        let yPosRight = columnsStartY;
        const gutter = 10;
        const colWidth = (contentW - gutter) / 2;
        const col1X = margin;
        const col2X = margin + colWidth + gutter;

        // Left Column: Ingredients
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(textColorDark);
        doc.text(language === 'es' ? 'Ingredientes' : 'Ingredients', col1X, yPosLeft);
        yPosLeft += 7;

        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(textColorMedium);
        recipe.ingredients.forEach(ing => {
            const stapleText = ing.isStaple ? (language === 'es' ? ' (Sugerido)' : ' (Suggested)') : '';
            const ingText = `• ${ing.quantity} ${ing.name}${stapleText}`;
            const ingLines = doc.splitTextToSize(ingText, colWidth);
            if (yPosLeft + ingLines.length * 4 > pageBottom) {
                 doc.text('...', col1X + 2, yPosLeft);
                 yPosLeft = pageBottom + 1; // Mark as overflowed
                 return;
            }
            if(yPosLeft > pageBottom) return;
            doc.text(ingLines, col1X + 2, yPosLeft);
            yPosLeft += ingLines.length * 4 + 1.5;
        });

        // Right Column: Instructions
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(textColorDark);
        doc.text(language === 'es' ? 'Instrucciones' : 'Instructions', col2X, yPosRight);
        yPosRight += 7;

        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(textColorMedium);
        doc.setLineHeightFactor(1.3);
        recipe.instructions.forEach((step, index) => {
            const stepText = `${index + 1}. ${step}`;
            const stepLines = doc.splitTextToSize(stepText, colWidth);
            if (yPosRight + (stepLines.length * 3.5 * 1.3) > pageBottom) {
                doc.text('...', col2X, yPosRight);
                yPosRight = pageBottom + 1; // Mark as overflowed
                return;
            }
            if(yPosRight > pageBottom) return;
            doc.text(stepLines, col2X, yPosRight);
            yPosRight += (stepLines.length * 3.5 * 1.3) + 3;
        });
        doc.setLineHeightFactor(1.0);

        yPos = Math.min(pageBottom, Math.max(yPosLeft, yPosRight));

        // --- 7. Health Tip (if space allows) ---
        if (recipe.healthTip && yPos < pageBottom - 25) {
            yPos += 10;
            const tipText = `"${recipe.healthTip}"`;
            const tipLines = doc.splitTextToSize(tipText, contentW - 10);
            const tipBoxHeight = tipLines.length * 4 * 1.4 + 12;
            
            doc.setFillColor('#f0fdf4'); // green-50
            doc.roundedRect(margin, yPos, contentW, tipBoxHeight, 3, 3, 'F');
            
            let tipY = yPos + 6;
            
            doc.setFontSize(10);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(primaryColor);
            doc.text(language === 'es' ? 'Consejo Saludable' : 'Healthy Tip', margin + 5, tipY);
            tipY += 5;

            doc.setFontSize(9);
            doc.setFont('helvetica', 'italic');
            doc.setTextColor(textColorMedium);
            doc.setLineHeightFactor(1.4);
            doc.text(tipLines, margin + 5, tipY);
            doc.setLineHeightFactor(1.0);
        }
        
        // --- 8. Footer ---
        addFooter();
        doc.save(`${recipe.recipeName.replace(/\s+/g, '_').toLowerCase()}.pdf`);
    };

    return (
        <div className="relative bg-white rounded-xl shadow-lg overflow-hidden transition-all duration-300 hover:shadow-2xl hover:-translate-y-1 border-t-4 border-green-500">
            <button
                onClick={() => onToggleFavorite(recipe)}
                className="absolute top-4 right-4 z-10 p-2 bg-white/80 backdrop-blur-sm rounded-full text-red-500 hover:bg-white transition-colors duration-200"
                aria-label={isFavorite ? (language === 'es' ? 'Quitar de favoritos' : 'Remove from favorites') : (language === 'es' ? 'Añadir a favoritos' : 'Add to favorites')}
            >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" viewBox="0 0 20 20" fill={isFavorite ? "currentColor" : "none"} stroke="currentColor" strokeWidth="1.5">
                    <path fillRule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clipRule="evenodd" />
                </svg>
            </button>
            
            {recipe.imageUrl ? (
                <img src={recipe.imageUrl} alt={recipe.recipeName} className="w-full h-64 object-cover" />
            ) : (
                <ImagePlaceholder />
            )}
            <div className="p-6 md:p-8">
                <h3 className="text-2xl sm:text-3xl font-bold text-slate-800 mb-2">{recipe.recipeName}</h3>
                <p className="text-slate-600 mb-6">{recipe.description}</p>

                <div className="flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-700 mb-6 border-b border-t border-slate-200 py-4">
                    <div className="flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-green-500" viewBox="0 0 20 20" fill="currentColor"><path d="M9 6a3 3 0 11-6 0 3 3 0 016 0zM17 6a3 3 0 11-6 0 3 3 0 016 0zM12.93 17c.046-.327.07-.66.07-1a6.97 6.97 0 00-1.5-4.33A5 5 0 0119 16v1h-6.07zM6 11a5 5 0 015 5v1H1v-1a5 5 0 015-5z" /></svg>
                        <strong>{language === 'es' ? 'Raciones:' : 'Servings:'}</strong> {recipe.servings}
                    </div>
                    <div className="flex items-center gap-2">
                         <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-green-500" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.414-1.414L11 10.586V6z" clipRule="evenodd" /></svg>
                        <strong>Prep:</strong> {recipe.prepTime}
                    </div>
                     <div className="flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                           <path fillRule="evenodd" d="M12.316 3.051a1 1 0 01.633 1.265l-4 12a1 1 0 01-1.898-.632l4-12a1 1 0 011.265-.633zM5.707 6.293a1 1 0 010 1.414L3.414 10l2.293 2.293a1 1 0 11-1.414 1.414l-3-3a1 1 0 010-1.414l3-3a1 1 0 011.414 0zm8.586 0a1 1 0 011.414 0l3 3a1 1 0 010 1.414l-3 3a1 1 0 11-1.414-1.414L16.586 10l-2.293-2.293a1 1 0 010-1.414z" clipRule="evenodd" />
                        </svg>
                        <strong>Cook:</strong> {recipe.cookTime}
                    </div>
                     <div className="flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                            <path fillRule="evenodd" d="M11.3 1.046A1 1 0 0112 2v5h4a1 1 0 01.82 1.573l-7 10A1 1 0 018 18v-5H4a1 1 0 01-.82-1.573l7-10a1 1 0 011.12-.38z" clipRule="evenodd" />
                        </svg>
                        <strong>Calories:</strong> ~{recipe.calories} kcal
                    </div>
                </div>

                {recipe.nutrition && (
                    <div className="grid grid-cols-3 gap-1 sm:gap-4 text-center mb-6 p-4 bg-slate-50 rounded-lg border border-slate-200">
                        <div>
                            <p className="text-xs text-slate-500 font-semibold uppercase tracking-wider">{language === 'es' ? 'Proteína' : 'Protein'}</p>
                            <p className="text-xl font-bold text-green-600">{recipe.nutrition.protein}</p>
                        </div>
                        <div>
                            <p className="text-xs text-slate-500 font-semibold uppercase tracking-wider">{language === 'es' ? 'Carbs' : 'Carbs'}</p>
                            <p className="text-xl font-bold text-green-600">{recipe.nutrition.carbs}</p>
                        </div>
                        <div>
                            <p className="text-xs text-slate-500 font-semibold uppercase tracking-wider">{language === 'es' ? 'Grasas' : 'Fats'}</p>
                            <p className="text-xl font-bold text-green-600">{recipe.nutrition.fats}</p>
                        </div>
                    </div>
                )}


                <div className="mb-8">
                    <DifficultyMeter difficulty={recipe.difficulty} language={language}/>
                </div>

                <div className="space-y-8">
                    <div>
                        <h4 className="text-xl font-semibold text-slate-700 mb-3 border-b-2 border-slate-200 pb-2">{language === 'es' ? 'Ingredientes' : 'Ingredients'}</h4>
                        <ul className="space-y-2 text-slate-600 list-disc list-inside">
                            {recipe.ingredients.map((ing, index) => (
                                <li key={index} className="pl-2">
                                    <span className="font-medium text-slate-800">{ing.quantity}</span> {ing.name}
                                    {ing.isStaple && <span className="ml-2 text-xs font-semibold bg-sky-100 text-sky-700 px-2 py-0.5 rounded-full">{language === 'es' ? 'Sugerido' : 'Suggested'}</span>}
                                </li>
                            ))}
                        </ul>
                    </div>
                    <div>
                        <h4 className="text-xl font-semibold text-slate-700 mb-3 border-b-2 border-slate-200 pb-2">{language === 'es' ? 'Instrucciones' : 'Instructions'}</h4>
                        <ol className="space-y-4 text-slate-600 list-decimal list-inside leading-relaxed">
                            {recipe.instructions.map((step, index) => (
                                <li key={index} className="pl-2">{step}</li>
                            ))}
                        </ol>
                    </div>

                    {recipe.healthTip && (
                        <div className="bg-green-50 p-4 rounded-lg border-l-4 border-green-400">
                            <h4 className="text-lg font-semibold text-green-800 mb-2">{language === 'es' ? 'Consejo Saludable' : 'Healthy Tip'}</h4>
                            <p className="text-green-700 italic">{recipe.healthTip}</p>
                        </div>
                    )}

                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-4 border-t border-slate-200">
                         <button
                            onClick={() => onShare(recipe)}
                            className="w-full flex items-center justify-center gap-2 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold py-3 px-4 rounded-lg transition-colors duration-300"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                <path d="M15 8a3 3 0 10-2.977-2.63l-4.94 2.47a3 3 0 100 4.319l4.94 2.47a3 3 0 10.895-1.789l-4.94-2.47a3.027 3.027 0 000-.74l4.94-2.47C13.456 7.68 14.19 8 15 8z" />
                            </svg>
                            {language === 'en' ? 'Share Recipe' : 'Compartir Receta'}
                        </button>
                        <button
                            onClick={handleDownloadPdf}
                            className="w-full flex items-center justify-center gap-2 bg-slate-600 hover:bg-slate-700 text-white font-bold py-3 px-4 rounded-lg transition-colors duration-300"
                        >
                             <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                <path fillRule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clipRule="evenodd" />
                            </svg>
                            {language === 'en' ? 'Download PDF' : 'Descargar PDF'}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default RecipeCard;